In [1]:
import pandas as pd

from datetime import datetime

df = pd.read_csv('/content/drive/MyDrive/glassdoor_cleaned.csv')

In [2]:
df.head()

,review_id,rating_date,employee_length,employee_status,employee_type,flags_business_outlook,flags_ceo_approval,flags_recommend_frend,rating_culture_values,rating_diversity_inclusion,...,rating_work_life,summary,career_opportunities_rating,employee_location,employee_job_title,advice_to_management,review_pros,review_cons,rating_senior_leadership,rating_compensation_benefits
0,1,2025-06-03,0,REGULAR,Current employee,NaN,NaN,NaN,0.0,0.0,...,0.0,Amazon,NaN,"Richmond, VA",Warehouse Fulfillment Associate,don’t micro manage,not interactive \ncan leave or take off whenev...,inhumane \ndraining physically &amp; mentally,0.0,0.0
1,2,2025-05-29,1,CONTRACT,"Current employee, less than 1 year",POSITIVE,APPROVE,POSITIVE,5.0,5.0,...,3.0,Good,NaN,"Brampton, ON",Warehouse Associate,Remove all attitude manager from warehouse,good and easy work enviorment,"Sticks rules and completing targets any how, o...",3.0,5.0
2,3,2025-05-28,1,REGULAR,"Current employee, less than 1 year",POSITIVE,APPROVE,POSITIVE,5.0,5.0,...,5.0,Good experience,NaN,"Bolton, ON",Warehouse Associate,NaN,"help to grow , good pay ,","limited opportunities for advancement,No clear...",5.0,5.0
3,4,2025-05-26,2,PART_TIME,Current employees,POSITIVE,APPROVE,POSITIVE,2.0,2.0,...,2.0,Dhdh,NaN,"Swedesboro, NJ",Employee,NaN,Plenty of work\nMeet new people,Tough on the body\nLabor intensive,2.0,2.0
4,5,2025-05-23,0,REGULAR,Current employee,NaN,NaN,NaN,0.0,0.0,...,0.0,Good Pay rate,NaN,"Whitby, ON",Fulfillment Associate,NaN,Good Holiday pay \nAdditional benefits for per...,Not hiring permanent employees directly,0.0,0.0

In [3]:
df['rating_date'] = pd.to_datetime(df['rating_date'], format='%Y-%m-%d')

df['rating_date'] = df['rating_date'].dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")
df.head()

,review_id,rating_date,employee_length,employee_status,employee_type,flags_business_outlook,flags_ceo_approval,flags_recommend_frend,rating_culture_values,rating_diversity_inclusion,...,rating_work_life,summary,career_opportunities_rating,employee_location,employee_job_title,advice_to_management,review_pros,review_cons,rating_senior_leadership,rating_compensation_benefits
0,1,2025-06-03T00:00:00.000Z,0,REGULAR,Current employee,NaN,NaN,NaN,0.0,0.0,...,0.0,Amazon,NaN,"Richmond, VA",Warehouse Fulfillment Associate,don’t micro manage,not interactive \ncan leave or take off whenev...,inhumane \ndraining physically &amp; mentally,0.0,0.0
1,2,2025-05-29T00:00:00.000Z,1,CONTRACT,"Current employee, less than 1 year",POSITIVE,APPROVE,POSITIVE,5.0,5.0,...,3.0,Good,NaN,"Brampton, ON",Warehouse Associate,Remove all attitude manager from warehouse,good and easy work enviorment,"Sticks rules and completing targets any how, o...",3.0,5.0
2,3,2025-05-28T00:00:00.000Z,1,REGULAR,"Current employee, less than 1 year",POSITIVE,APPROVE,POSITIVE,5.0,5.0,...,5.0,Good experience,NaN,"Bolton, ON",Warehouse Associate,NaN,"help to grow , good pay ,","limited opportunities for advancement,No clear...",5.0,5.0
3,4,2025-05-26T00:00:00.000Z,2,PART_TIME,Current employees,POSITIVE,APPROVE,POSITIVE,2.0,2.0,...,2.0,Dhdh,NaN,"Swedesboro, NJ",Employee,NaN,Plenty of work\nMeet new people,Tough on the body\nLabor intensive,2.0,2.0
4,5,2025-05-23T00:00:00.000Z,0,REGULAR,Current employee,NaN,NaN,NaN,0.0,0.0,...,0.0,Good Pay rate,NaN,"Whitby, ON",Fulfillment Associate,NaN,Good Holiday pay \nAdditional benefits for per...,Not hiring permanent employees directly,0.0,0.0

In [4]:
print(df['rating_date'])

0      2025-06-03T00:00:00.000Z
1      2025-05-29T00:00:00.000Z
2      2025-05-28T00:00:00.000Z
3      2025-05-26T00:00:00.000Z
4      2025-05-23T00:00:00.000Z
                 ...
128    2026-01-31T00:00:00.000Z
129    2026-01-29T00:00:00.000Z
130    2026-01-28T00:00:00.000Z
131    2026-01-28T00:00:00.000Z
132    2026-01-27T00:00:00.000Z
Name: rating_date, Length: 133, dtype: object

In [5]:
df = df.drop(columns = ['summary'])

In [6]:
columns_to_process = ['flags_ceo_approval', 'flags_business_outlook', 'flags_recommend_frend', 'employee_status']

for col in columns_to_process:

    df[col] = df[col].astype(str).str.upper()

df.head()

,review_id,rating_date,employee_length,employee_status,employee_type,flags_business_outlook,flags_ceo_approval,flags_recommend_frend,rating_culture_values,rating_diversity_inclusion,rating_overall,rating_work_life,career_opportunities_rating,employee_location,employee_job_title,advice_to_management,review_pros,review_cons,rating_senior_leadership,rating_compensation_benefits
0,1,2025-06-03T00:00:00.000Z,0,REGULAR,Current employee,NAN,NAN,NAN,0.0,0.0,3,0.0,NaN,"Richmond, VA",Warehouse Fulfillment Associate,don’t micro manage,not interactive \ncan leave or take off whenev...,inhumane \ndraining physically &amp; mentally,0.0,0.0
1,2,2025-05-29T00:00:00.000Z,1,CONTRACT,"Current employee, less than 1 year",POSITIVE,APPROVE,POSITIVE,5.0,5.0,4,3.0,NaN,"Brampton, ON",Warehouse Associate,Remove all attitude manager from warehouse,good and easy work enviorment,"Sticks rules and completing targets any how, o...",3.0,5.0
2,3,2025-05-28T00:00:00.000Z,1,REGULAR,"Current employee, less than 1 year",POSITIVE,APPROVE,POSITIVE,5.0,5.0,5,5.0,NaN,"Bolton, ON",Warehouse Associate,NaN,"help to grow , good pay ,","limited opportunities for advancement,No clear...",5.0,5.0
3,4,2025-05-26T00:00:00.000Z,2,PART_TIME,Current employees,POSITIVE,APPROVE,POSITIVE,2.0,2.0,3,2.0,NaN,"Swedesboro, NJ",Employee,NaN,Plenty of work\nMeet new people,Tough on the body\nLabor intensive,2.0,2.0
4,5,2025-05-23T00:00:00.000Z,0,REGULAR,Current employee,NAN,NAN,NAN,0.0,0.0,4,0.0,NaN,"Whitby, ON",Fulfillment Associate,NaN,Good Holiday pay \nAdditional benefits for per...,Not hiring permanent employees directly,0.0,0.0

In [7]:
df.to_csv('glassdoor_cleaned_V2.csv')